from __future__ import annotations

import copy
import json
import re
from dataclasses import dataclass, field
from typing import Any, Callable, Dict, Iterable, List, Mapping, Optional, Sequence, Tuple

from argumentation_graph import ArgumentationGraph, NodeType, RelationType


ARGUMENT_EXTRACTION_SYSTEM_PROMPT = (
    "You are an argumentation analyst specializing in computational "
    "argumentation. Your role is to extract structured arguments from "
    "unstructured text responses generated by language models in a "
    "multi-agent debate setting."
)

REFINEMENT_SYSTEM_PROMPT = (
    "You are an expert reasoning agent participating in a structured "
    "multi-agent debate framework. Your primary objective is to resolve "
    "unresolved argumentative conflicts using evidence-aware reasoning. You "
    "must critically evaluate competing claims, identify logical fallacies "
    "or weak assumptions, and produce a justifiable conclusion."
)


@dataclass(frozen=True)
class Conflict:
    source_id: str
    target_id: str
    score: float = 1.0
    relation: str = RelationType.ATTACKS.value

    @property
    def key(self) -> Tuple[str, str]:
        return self.source_id, self.target_id


@dataclass
class RefinementResult:
    graph: ArgumentationGraph
    selected_conflicts: List[Conflict] = field(default_factory=list)
    contexts: Dict[Tuple[str, str], Any] = field(default_factory=dict)
    responses: List[str] = field(default_factory=list)
    updated_node_ids: List[str] = field(default_factory=list)
    inconsistency_before: float = 0.0
    inconsistency_after: float = 0.0

    @property
    def selected(self) -> List[Conflict]:
        return self.selected_conflicts


def _nodes(graph: Any) -> Mapping[str, Any]:
    if hasattr(graph, "nodes"):
        return graph.nodes
    return graph.get("nodes", {})


def _edges(graph: Any) -> Iterable[Any]:
    if hasattr(graph, "edges"):
        return graph.edges
    return graph.get("edges", [])


def _value(item: Any, *names: str, default: Any = None) -> Any:
    for name in names:
        if isinstance(item, Mapping) and name in item:
            return item[name]
        if hasattr(item, name):
            return getattr(item, name)
    return default


def _node_id(item: Any) -> str:
    return str(_value(item, "node_id", "id", default=""))


def _relation(item: Any) -> str:
    relation = _value(item, "relation", "type", default="")
    if isinstance(relation, RelationType):
        return relation.value
    return str(relation).lower()


def _relation_enum(value: Any) -> RelationType:
    if isinstance(value, RelationType):
        return value
    normalized = str(value).lower()
    aliases = {
        "support": RelationType.SUPPORTS,
        "supports": RelationType.SUPPORTS,
        "attack": RelationType.ATTACKS,
        "attacks": RelationType.ATTACKS,
        "citation": RelationType.CITES,
        "cite": RelationType.CITES,
        "cites": RelationType.CITES,
        "derives_from": RelationType.DERIVES_FROM,
    }
    if normalized not in aliases:
        raise ValueError(f"Unsupported relation type: {value}")
    return aliases[normalized]


def _node_type(value: Any) -> NodeType:
    if isinstance(value, NodeType):
        return value
    normalized = str(value).lower()
    aliases = {
        "claim": NodeType.CLAIM,
        "evidence": NodeType.EVIDENCE,
        "assumption": NodeType.ASSUMPTION,
        "conclusion": NodeType.CONCLUSION,
        "question": NodeType.QUESTION,
    }
    return aliases.get(normalized, NodeType.CLAIM)


def _edge_endpoints(edge: Any) -> Tuple[str, str]:
    return (
        str(_value(edge, "source_id", "source", default="")),
        str(_value(edge, "target_id", "target", default="")),
    )


def _edge_strength(edge: Any) -> float:
    try:
        return float(_value(edge, "strength", "weight", default=0.5))
    except (TypeError, ValueError):
        return 0.5


def _conflict(value: Any) -> Conflict:
    if isinstance(value, Conflict):
        return value
    if isinstance(value, Mapping):
        source, target = _edge_endpoints(value)
        return Conflict(source, target, float(value.get("score", 1.0)))
    if isinstance(value, Sequence) and len(value) >= 2:
        return Conflict(str(value[0]), str(value[1]))
    raise TypeError(f"Unsupported conflict value: {type(value)!r}")


def detect_unresolved_conflicts(graph: Any) -> List[Conflict]:
    attacks = set()
    supports = set()
    for edge in _edges(graph):
        source, target = _edge_endpoints(edge)
        if source not in _nodes(graph) or target not in _nodes(graph):
            continue
        if _relation(edge) == RelationType.ATTACKS.value:
            attacks.add((source, target))
        elif _relation(edge) == RelationType.SUPPORTS.value:
            supports.add((source, target))
    return [
        Conflict(source, target)
        for source, target in sorted(attacks)
        if not any(attacked == source for _, attacked in attacks)
        and not any(supported == target for _, supported in supports)
    ]


def compute_graph_inconsistency(
    graph: Any,
    unresolved_conflicts: Optional[Iterable[Conflict]] = None,
) -> float:
    attack_pairs = {
        _edge_endpoints(edge)
        for edge in _edges(graph)
        if _relation(edge) == RelationType.ATTACKS.value
        and _edge_endpoints(edge)[0] in _nodes(graph)
        and _edge_endpoints(edge)[1] in _nodes(graph)
    }
    if not attack_pairs:
        return 0.0
    conflicts = (
        list(unresolved_conflicts)
        if unresolved_conflicts is not None
        else detect_unresolved_conflicts(graph)
    )
    unresolved = {(_conflict(item).source_id, _conflict(item).target_id) for item in conflicts}
    return len(unresolved & attack_pairs) / len(attack_pairs)


def _relation_weight(relation: str) -> float:
    return {
        RelationType.ATTACKS.value: 1.0,
        RelationType.SUPPORTS.value: 0.8,
        RelationType.CITES.value: 0.5,
        RelationType.DERIVES_FROM.value: 0.5,
    }.get(relation, 0.5)


def _directed_matrix(graph: Any) -> Dict[str, Dict[str, float]]:
    node_ids = set(_nodes(graph))
    matrix = {node_id: {} for node_id in node_ids}
    for edge in _edges(graph):
        source, target = _edge_endpoints(edge)
        if source not in node_ids or target not in node_ids:
            continue
        relation = _relation(edge)
        weight = max(0.0, _edge_strength(edge)) * _relation_weight(relation)
        matrix[source][target] = matrix[source].get(target, 0.0) + weight
    return matrix


def _outgoing_neighbors(graph: Any, node_id: str) -> List[str]:
    result = []
    for edge in _edges(graph):
        source, target = _edge_endpoints(edge)
        if source == node_id and target in _nodes(graph):
            result.append(target)
    return result


def _incoming_neighbors(graph: Any, node_id: str) -> List[str]:
    result = []
    for edge in _edges(graph):
        source, target = _edge_endpoints(edge)
        if target == node_id and source in _nodes(graph):
            result.append(source)
    return result


def propagate_conflict_utility(
    graph: Any,
    conflicts: Optional[Iterable[Conflict]] = None,
    propagation_steps: int = 3,
    retrieval_hops: int = 3,
    damping: Optional[float] = None,
) -> Dict[Tuple[str, str], float]:
    selected = [_conflict(item) for item in (conflicts or detect_unresolved_conflicts(graph))]
    if not selected:
        return {}
    matrix = _directed_matrix(graph)
    adjacency = {node_id: {} for node_id in _nodes(graph)}
    for source, targets in matrix.items():
        total = sum(targets.values())
        if total <= 0:
            continue
        for target, weight in targets.items():
            adjacency.setdefault(target, {})[source] = weight / total

    utilities = {}
    for item in selected:
        region = retrieve_khop_subgraph(graph, item, retrieval_hops)
        region_ids = set(_nodes(region))
        influence = {node_id: 0.0 for node_id in _nodes(graph)}
        influence[item.source_id] = float(item.score)
        influence[item.target_id] = float(item.score)
        for _ in range(max(0, int(propagation_steps))):
            next_influence = {node_id: 0.0 for node_id in influence}
            for target, sources in adjacency.items():
                next_influence[target] = sum(
                    weight * influence.get(source, 0.0)
                    for source, weight in sources.items()
                )
            if damping is not None and 0.0 <= damping < 1.0:
                next_influence = {
                    node_id: damping * next_influence[node_id]
                    + (1.0 - damping) * influence.get(node_id, 0.0)
                    for node_id in next_influence
                }
            influence = next_influence
        utilities[item.key] = sum(influence.get(node_id, 0.0) for node_id in region_ids)
    return utilities


def select_topk_conflicts(
    conflicts: Iterable[Conflict],
    utilities: Mapping[Tuple[str, str], float],
    k: int = 1,
) -> List[Conflict]:
    ordered = sorted(
        (_conflict(item) for item in conflicts),
        key=lambda item: (-float(utilities.get(item.key, item.score)), item.key),
    )
    return ordered[: max(0, int(k))]


def _induced_graph(graph: ArgumentationGraph, node_ids: Iterable[str]) -> ArgumentationGraph:
    node_ids = set(node_ids)
    result = ArgumentationGraph()
    mapping = {}
    for node_id in _nodes(graph):
        if node_id not in node_ids:
            continue
        node = _nodes(graph)[node_id]
        generated_id = result.add_node(
            _value(node, "content", "text", default=""),
            _node_type(_value(node, "node_type", "type", default="claim")),
            int(_value(node, "agent_id", "agent", default=0)),
            int(_value(node, "round", default=0)),
            float(_value(node, "confidence", default=0.5)),
            copy.deepcopy(_value(node, "metadata", default={}) or {}),
        )
        copied = result.nodes.pop(generated_id)
        copied.node_id = node_id
        result.nodes[node_id] = copied
        mapping[node_id] = node_id
    for edge in _edges(graph):
        source, target = _edge_endpoints(edge)
        if source in mapping and target in mapping:
            result.add_edge(
                mapping[source],
                mapping[target],
                _relation_enum(_relation(edge)),
                _edge_strength(edge),
            )
    return result


def retrieve_khop_subgraph(
    graph: Any,
    conflict: Conflict,
    k: int = 3,
    direction: str = "incident",
) -> Any:
    item = _conflict(conflict)
    if item.source_id not in _nodes(graph) or item.target_id not in _nodes(graph):
        raise ValueError("Conflict endpoints must exist in the graph")
    visited = {item.source_id, item.target_id}
    frontier = set(visited)
    for _ in range(max(0, int(k))):
        next_frontier = set()
        for node_id in frontier:
            if direction in {"out", "both", "incident"}:
                next_frontier.update(_outgoing_neighbors(graph, node_id))
            if direction in {"in", "both", "incident"}:
                next_frontier.update(_incoming_neighbors(graph, node_id))
        next_frontier -= visited
        visited.update(next_frontier)
        frontier = next_frontier
        if not frontier:
            break
    if hasattr(graph, "nodes") and hasattr(graph, "edges"):
        return _induced_graph(graph, visited)
    return {
        "nodes": {node_id: _nodes(graph)[node_id] for node_id in visited},
        "edges": [
            edge
            for edge in _edges(graph)
            if _edge_endpoints(edge)[0] in visited and _edge_endpoints(edge)[1] in visited
        ],
    }


def serialize_subgraph(graph: Any) -> str:
    nodes = []
    for node_id, node in _nodes(graph).items():
        nodes.append(
            {
                "id": node_id,
                "type": _node_type(_value(node, "node_type", "type", default="claim")).value,
                "text": _value(node, "content", "text", default=""),
                "agent": _value(node, "agent_id", "agent", default=0),
                "round": _value(node, "round", default=0),
                "confidence": _value(node, "confidence", default=0.5),
            }
        )
    edges = []
    for edge in _edges(graph):
        source, target = _edge_endpoints(edge)
        edges.append(
            {
                "source": source,
                "target": target,
                "relation": _relation(edge),
                "strength": _edge_strength(edge),
            }
        )
    return json.dumps({"nodes": nodes, "relations": edges}, ensure_ascii=False, indent=2)


def build_argument_extraction_prompt(response_text: str) -> str:
    return (
        "Response: The following is an agent's response from a debate round. "
        "Analyze the underlying argumentative structure.\n\n"
        "Task Description: Extract claims, evidence, assumptions, and "
        "conclusions. Return a JSON object with nodes and relations. Each node "
        "must contain id, type, text, and confidence. Each relation must "
        "contain source, target, type, rationale, and confidence. Use only "
        "claim/evidence/assumption/conclusion for node types and "
        "support/attack/citation for relation types. Only output extracted "
        "arguments, omit absent categories, and keep long spans under 200 "
        "characters.\n\n"
        f"Agent response:\n{response_text}"
    )


def _client_text(client: Any, model: str, system: str, prompt: str) -> str:
    response = client.chat.completions.create(
        model=model,
        temperature=0,
        messages=[
            {"role": "system", "content": system},
            {"role": "user", "content": prompt},
        ],
    )
    content = response.choices[0].message.content
    return str(content or "").strip()


def _strip_fence(text: str) -> str:
    cleaned = text.strip()
    fence = chr(96) * 3
    if cleaned.startswith(fence):
        cleaned = cleaned.split("\n", 1)[-1]
        if cleaned.endswith(fence):
            cleaned = cleaned[:-3]
    return cleaned.strip()


def extract_arguments_with_llm(
    client: Any,
    response_text: str,
    model: str = "gpt-4o",
) -> Dict[str, Any]:
    raw = _client_text(
        client,
        model,
        ARGUMENT_EXTRACTION_SYSTEM_PROMPT,
        build_argument_extraction_prompt(response_text),
    )
    payload = json.loads(_strip_fence(raw))
    if not isinstance(payload, dict):
        raise ValueError("Argument extraction response must be a JSON object")
    payload.setdefault("nodes", [])
    payload.setdefault("relations", [])
    if not isinstance(payload["nodes"], list) or not isinstance(payload["relations"], list):
        raise ValueError("Argument extraction fields must be arrays")
    return payload


def integrate_extraction(
    graph: ArgumentationGraph,
    extraction: Mapping[str, Any],
    agent_id: int,
    round_num: int,
    response_text: str = "",
) -> Dict[str, str]:
    local_to_graph = {}
    existing = {
        (
            str(_value(node, "content", default="")).strip(),
            _node_type(_value(node, "node_type", default="claim")),
        ): node_id
        for node_id, node in graph.nodes.items()
    }
    for item in extraction.get("nodes", []):
        local_id = str(item.get("id", ""))
        text = str(item.get("text", "")).strip()
        if not local_id or not text:
            continue
        node_type = _node_type(item.get("type", "claim"))
        key = (text, node_type)
        node_id = existing.get(key)
        if node_id is None:
            node_id = graph.add_node(
                text,
                node_type,
                agent_id,
                round_num,
                float(item.get("confidence", 0.5)),
                {"extraction_id": local_id, "response": response_text},
            )
            existing[key] = node_id
        local_to_graph[local_id] = node_id
    for item in extraction.get("relations", []):
        source = local_to_graph.get(str(item.get("source", "")))
        target = local_to_graph.get(str(item.get("target", "")))
        if source is None or target is None:
            continue
        relation = _relation_enum(item.get("type", "supports"))
        duplicate = any(
            edge.source_id == source
            and edge.target_id == target
            and edge.relation == relation
            for edge in graph.edges
        )
        if not duplicate:
            graph.add_edge(source, target, relation, float(item.get("confidence", 0.5)))
    return local_to_graph


def _context_nodes(subgraph: Any, node_type: NodeType) -> str:
    values = []
    for node in _nodes(subgraph).values():
        if _node_type(_value(node, "node_type", "type", default="claim")) == node_type:
            values.append(f"- {_value(node, 'content', 'text', default='')}")
    return "\n".join(values) or "- None explicitly identified"


def _refinement_prompt(
    question: str,
    history: Sequence[str],
    conflict: Conflict,
    subgraph: Any,
) -> str:
    history_text = "\n".join(str(item) for item in history)
    local_nodes = _nodes(subgraph)
    claim_a = _value(local_nodes.get(conflict.source_id), "content", "text", default=conflict.source_id)
    claim_b = _value(local_nodes.get(conflict.target_id), "content", "text", default=conflict.target_id)
    return (
        "Original Question:\n"
        f"{question}\n\n"
        "Unresolved Conflict:\n"
        f"- Claim A: {claim_a}\n"
        f"- Claim B: {claim_b}\n\n"
        "Supporting Evidence:\n"
        f"{_context_nodes(subgraph, NodeType.EVIDENCE)}\n\n"
        "Related Assumptions:\n"
        f"{_context_nodes(subgraph, NodeType.ASSUMPTION)}\n\n"
        "Neighboring Counter-Arguments:\n"
        f"{_context_nodes(subgraph, NodeType.CLAIM)}\n\n"
        "Debate History:\n"
        f"{history_text}\n\n"
        "Localized Graph Representation:\n"
        f"{serialize_subgraph(subgraph)}\n\n"
        "Task Description: Analyze the structural conflict and complete all "
        "five tasks: (1) identify unsupported or weak assumptions; (2) resolve "
        "semantic or logical inconsistencies when possible; (3) introduce "
        "additional supporting evidence when needed; (4) preserve logically "
        "consistent conclusions; and (5) explain why one claim is preferred "
        "or propose a synthesis if both have merit. Integrate new arguments "
        "into the textual content of existing nodes rather than creating "
        "nodes.\n\n"
        "Output Requirements: Return these four semantic fields using the exact "
        "headings below:\n"
        "[New Claims]\n"
        "[Supporting Evidence]\n"
        "[Resolution]\n"
        "[Refined Conclusion]\n"
        "Use concise natural language. Do not return JSON or an instruction "
        "to update graph objects."
    )


def _client_response(
    client: Any,
    model: str,
    prompt: str,
) -> str:
    return _client_text(client, model, REFINEMENT_SYSTEM_PROMPT, prompt)


def _invoke_refiner(refine_fn: Callable[..., Any], prompt: str, context: Any) -> str:
    try:
        value = refine_fn(prompt, context)
    except TypeError:
        value = refine_fn(prompt)
    if isinstance(value, str):
        return value
    if isinstance(value, Mapping):
        fields = []
        for key in ("new_claims", "supporting_evidence", "resolution", "refined_conclusion"):
            if key in value:
                fields.append(f"[{key.replace('_', ' ').title()}]\n{value[key]}")
        return "\n".join(fields)
    return str(value)


def _sections(text: str) -> Dict[str, str]:
    headings = [
        "New Claims",
        "Supporting Evidence",
        "Resolution",
        "Refined Conclusion",
    ]
    result = {heading: "" for heading in headings}
    pattern = re.compile(
        r"\[(New Claims|Supporting Evidence|Resolution|Refined Conclusion)\]\s*",
        re.IGNORECASE,
    )
    matches = list(pattern.finditer(text))
    for index, match in enumerate(matches):
        heading = next(
            item for item in headings if item.lower() == match.group(1).lower()
        )
        end = matches[index + 1].start() if index + 1 < len(matches) else len(text)
        result[heading] = text[match.end():end].strip()
    if not any(result.values()) and text.strip():
        result["Refined Conclusion"] = text.strip()
    return result


def _append_node_text(node: Any, sections: Mapping[str, str]) -> bool:
    additions = [
        f"[{heading}]\n{value}"
        for heading, value in sections.items()
        if value.strip()
    ]
    if not additions:
        return False
    content = str(_value(node, "content", default=""))
    addition = "\n\n".join(additions)
    if addition in content:
        return False
    node.content = f"{content}\n\n{addition}".strip()
    if sections.get("Refined Conclusion") and getattr(node, "node_type", None) == NodeType.ASSUMPTION:
        node.node_type = NodeType.CONCLUSION
    return True


def _tokens(text: str) -> set:
    return set(re.findall(r"[A-Za-z0-9]{3,}", str(text).lower()))


def _support_candidate(
    subgraph: Any,
    conflict: Conflict,
    evidence_text: str,
) -> Optional[str]:
    candidates = []
    evidence_tokens = _tokens(evidence_text)
    for node_id, node in _nodes(subgraph).items():
        if node_id in {conflict.source_id, conflict.target_id}:
            continue
        node_type = _node_type(_value(node, "node_type", "type", default="claim"))
        content = str(_value(node, "content", "text", default=""))
        priority = {
            NodeType.EVIDENCE: 3,
            NodeType.ASSUMPTION: 2,
            NodeType.CLAIM: 1,
            NodeType.CONCLUSION: 1,
        }.get(node_type, 0)
        overlap = len(evidence_tokens & _tokens(content))
        candidates.append((overlap, priority, node_id))
    if not candidates:
        return None
    candidates.sort(key=lambda item: (-item[0], -item[1], item[2]))
    return candidates[0][2]


def _add_edge_once(
    graph: ArgumentationGraph,
    source_id: str,
    target_id: str,
    relation: RelationType,
    strength: float = 0.5,
) -> bool:
    if source_id == target_id:
        return False
    if any(
        edge.source_id == source_id
        and edge.target_id == target_id
        and edge.relation == relation
        for edge in graph.edges
    ):
        return False
    graph.add_edge(source_id, target_id, relation, strength)
    return True


def _apply_refinement_relations(
    graph: ArgumentationGraph,
    conflict: Conflict,
    subgraph: Any,
    sections: Mapping[str, str],
) -> bool:
    changed = False
    supporting_text = sections.get("Supporting Evidence", "").strip()
    if supporting_text and supporting_text.lower() not in {"none", "none explicitly identified"}:
        candidate = _support_candidate(subgraph, conflict, supporting_text)
        if candidate is not None:
            changed |= _add_edge_once(
                graph,
                candidate,
                conflict.target_id,
                RelationType.SUPPORTS,
                0.7,
            )
    resolution = sections.get("Resolution", "").lower()
    if re.search(r"\b(refute|refutes|refuted|reject|rejects|disprove|unsupported)\b", resolution):
        changed |= _add_edge_once(
            graph,
            conflict.target_id,
            conflict.source_id,
            RelationType.ATTACKS,
            0.7,
        )
    return changed


def graph_conditioned_refinement(
    graph: ArgumentationGraph,
    conflict: Optional[Any] = None,
    subgraph: Optional[Any] = None,
    question: str = "",
    history: Optional[Sequence[str]] = None,
    refine_fn: Optional[Callable[..., Any]] = None,
    client: Optional[Any] = None,
    model: str = "gpt-4o",
    top_k: int = 1,
    k_hop: int = 3,
    agent_ids: Optional[Sequence[int]] = None,
    max_rounds: int = 3,
    inconsistency_threshold: float = 0.0,
) -> RefinementResult:
    if refine_fn is not None and client is not None:
        raise ValueError("Provide refine_fn or client, not both")
    history = list(history or [])
    all_conflicts = detect_unresolved_conflicts(graph)
    before = compute_graph_inconsistency(graph, all_conflicts)
    automatic = conflict is None
    if automatic:
        utilities = propagate_conflict_utility(graph, all_conflicts)
        selected = select_topk_conflicts(all_conflicts, utilities, top_k)
    elif isinstance(conflict, (list, tuple, set)) and not isinstance(conflict, Conflict):
        selected = [_conflict(item) for item in conflict]
    else:
        selected = [_conflict(conflict)]
    initial_selected = list(selected)
    contexts = {}
    for item in selected:
        contexts[item.key] = (
            subgraph
            if len(selected) == 1 and subgraph is not None
            else retrieve_khop_subgraph(graph, item, k_hop)
        )
    responses = []
    updated = []
    ids = list(agent_ids) if agent_ids is not None else [0, 1, 2]
    if refine_fn is None and client is None:
        return RefinementResult(
            graph,
            selected,
            contexts,
            responses,
            updated,
            before,
            compute_graph_inconsistency(graph),
        )
    if before <= inconsistency_threshold:
        return RefinementResult(
            graph,
            selected,
            contexts,
            responses,
            updated,
            before,
            before,
        )
    if not ids:
        ids = [0]
    rounds = max(1, int(max_rounds))
    for _ in range(rounds):
        current = detect_unresolved_conflicts(graph)
        if not current:
            break
        if automatic:
            utilities = propagate_conflict_utility(graph, current)
            active = select_topk_conflicts(current, utilities, top_k)
            for item in active:
                if item.key not in {entry.key for entry in initial_selected}:
                    initial_selected.append(item)
        else:
            active = [item for item in selected if item.key in {entry.key for entry in current}]
        if not active:
            break
        for item in active:
            if item.key not in contexts or automatic:
                contexts[item.key] = retrieve_khop_subgraph(graph, item, k_hop)
            local = contexts[item.key]
            prompt = _refinement_prompt(question, history, item, local)
            for agent_id in ids:
                response = (
                    _invoke_refiner(refine_fn, prompt, local)
                    if refine_fn is not None
                    else _client_response(client, model, prompt)
                )
                responses.append(response)
                parsed = _sections(response)
                target = graph.nodes.get(item.target_id)
                if target is not None and _append_node_text(target, parsed):
                    updated.append(item.target_id)
                _apply_refinement_relations(graph, item, local, parsed)
                history.append(f"agent {agent_id}: {response}")
        if compute_graph_inconsistency(graph) <= inconsistency_threshold:
            break
    after = compute_graph_inconsistency(graph)
    return RefinementResult(
        graph,
        initial_selected,
        contexts,
        responses,
        list(dict.fromkeys(updated)),
        before,
        after,
    )
